sudo: required

language: bash
#python:
#  - "2.7"
#  - "3.5"
#  - "3.6"
#  - "3.7-dev"

services:
  - docker

before_install:
- docker build -t zabbix  .
- docker images
- docker run --name mysql-server -t \
      -e MYSQL_DATABASE="zabbix" \
      -e MYSQL_USER="zabbix" \
      -e MYSQL_PASSWORD="zabbix_pwd" \
      -e MYSQL_ROOT_PASSWORD="root_pwd" \
      -d mysql:5.7 \
      --character-set-server=utf8 --collation-server=utf8_bin
- docker ps -a
